apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: cyclops-assets
  namespace: cyclops-assets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyclops-assets
  template:
    metadata:
      labels:
        app: cyclops-assets
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: cyclops-assets
              topologyKey: kubernetes.io/hostname
      containers:
      - name: cyclops-assets
        image: nginx:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "1500m"
          requests:
            memory: "20Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: assets
        - mountPath: /etc/nginx/conf.d
          name: assets-cm
        - mountPath: /etc/nginx/ssl
          name: ssl-certs
        - mountPath: /usr/share/nginx/html/.well-known
          name: well-known
        - mountPath: /usr/share/nginx/html/ssl-ca
          name: ssl-certs-ca
      volumes:
      - name: assets
        persistentVolumeClaim:
          claimName: assets
      - name: assets-cm
        configMap:
          name: assets
      - name: ssl-certs
        secret:
          secretName: assets-cyclops-tls
      - name: ssl-certs-ca
        secret:
          secretName: assets-cyclops-tls
          items:
          - key: ca.crt
            path: ca.crt
      - name: well-known
        configMap:
          defaultMode: 420
          name: well-known
