apiVersion: v1
kind: Service
metadata:
  name: assets
  namespace: cyclops-assets
spec:
  selector:
    app: cyclops-assets
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
