apiVersion: v1
kind: ConfigMap
metadata:
  name: assets
data:
  default.conf: |
    server {
        listen              80;
        listen              443 ssl;
        server_name         assets.cyclops-assets;
        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root   /usr/share/nginx/html;
        }
    }
