apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-assets
  namespace: cyclops-assets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyclops-assets
  template:
    metadata:
      labels:
        app: cyclops-assets
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: cyclops-assets
              topologyKey: kubernetes.io/hostname
      containers:
      - name: cyclops-assets
        image: nginx:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
          requests:
            memory: "20Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: assets
      volumes:
      - name: assets
        persistentVolumeClaim:
          claimName: assets
