apiVersion: v1
kind: ConfigMap
metadata:
  name: os-images
  namespace: cyclops-assets
data:
  urls: |
    https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
    https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-GenericCloud-10-latest.x86_64.qcow2
    https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    https://cloud-images.ubuntu.com/questing/current/questing-server-cloudimg-amd64.img

