apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-mirrors
  namespace: cyclops-assets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry-mirrors
  template:
    metadata:
      labels:
        app: registry-mirrors
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: registry-mirrors
              topologyKey: kubernetes.io/hostname
      containers:
      - name: proxy
        image: nginx:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
          requests:
            memory: "20Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: sites
      volumes:
      - name: sites
        configMap:
          name: registry-mirrors-proxy
