apiVersion: v1
kind: Service
metadata:
  name: registry-mirrors
  namespace: cyclops-assets
spec:
  selector:
    app: registry-mirrors
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
