apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-mirrors-cyclops
spec:
  commonName: registry-mirrors.cyclops-assets
  dnsNames:
  - registry-mirrors.cyclops-assets
  - registry-mirrors
  - localhost
  duration: 720h0m0s
  issuerRef:
    kind: Issuer
    name: certificate-authority
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  renewBefore: 480h0m0s
  secretName: registry-mirrors-cyclops-tls
  subject:
    organizations:
    - Cyclops-k8s
  usages:
  - server auth
  - client auth
